name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/optisign-bot:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set image output
        run: |
          echo "IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/optisign-bot:latest" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy to Self-Hosted
    runs-on: [self-hosted, linux, X64]
    needs: build

    steps:
      - name: Pull latest image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/optisign-bot:latest
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/optisign-bot:latest optibot:latest

      - name: Setup environment
        run: |
          chmod +x scripts/*.sh
          ./scripts/setup-environment.sh

      - name: Create environment file
        run: |
          cat > /opt/optibot/.env << EOF
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          ASSISTANT_ID=${{ secrets.ASSISTANT_ID }}
          VECTOR_STORE_ID=${{ secrets.VECTOR_STORE_ID }}
          MODEL=gpt-4o-mini
          CHUNK_SIZE=800
          CHUNK_OVERLAP=200
          LOCALE=en-us
          MAX_ARTICLES=45
          ARTICLES_DIR=./articles
          EOF

      - name: Stop existing containers
        run: |
          chmod +x scripts/*.sh
          ./scripts/cleanup-containers.sh

      - name: Setup cron job
        run: |
          chmod +x scripts/*.sh
          ./scripts/setup-cron.sh

      - name: Test deployment
        run: |
          chmod +x scripts/*.sh
          ./scripts/test-deployment.sh

      - name: Sync articles from container to host
        run: |
          echo "🔄 Syncing articles from container to host..."
          # Articles are already synced via volume mount, just verify
          echo "✅ Articles available on host: $(ls /opt/optibot/articles/*.md 2>/dev/null | wc -l) files"
